### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by stephenajulu** [stackbithq/stackbit-theme-ampersand#2]
Hi, could you kindly create for us a dark and light mode switch with the choice of setting dark mode as the default choice. If time is not on your hands kindly direct me which file and variable to change to achieve a website wide dark mode.

**Comment by stephenajulu** [comment]
I would really appreciate

**Comment by TomasBankauskas** [comment]
Hi, thank you for reaching out @stephenajulu. Regarding dark mode for Ampersand, you could check another Stackbit theme as an example - [Exto](https://github.com/stackbithq/stackbit-theme-exto). It has dark mode included. Not the way you described but you could use it as the base for functionality you wanted. Hope this helps.
