### ISSUE TITLE
Setting up Ampersand as a Jekyll theme

### ISSUE THREAD

**Issue by tashwoods** [stackbithq/stackbit-theme-ampersand#4]
Hi,
I love this theme and would like to use it in my jekyll blog. I tried adding:

Gemfile:
gem ampersand

$bundle install

And see:
Could not find gem 'Ampersand' in any of the gem sources listed in your Gemfile.

What is the proper way to install this as a jekyll theme?

**Comment by TomasBankauskas** [comment]
Hi @tashwoods, I'm glad to hear that you like the theme. Regarding your question, you can use the Stackbit page builder to convert this theme to Jekyll and use it for your blog. Click the **"Create With Stackbit"** button and follow instructions. After you completed the setup, the Stackbit page builder generates the Jekyll version of the Ampersand theme to your Github account repository. In this repository, you will find instructions in the Readme file on how to run the Jekyll theme locally. 

I hope this helps and happy blogging.

**Comment by tashwoods** [comment]
Awesome thank you for the help!
